# Disabling sudo moves build to the Container Based Infrastructure on Travis CI.
sudo: false

language: java
jdk: oraclejdk8

install:
  - echo "Overriding default Travis install step to avoid unnecessary './gradlew assemble'."

before_script:
  chmod +x build.sh
script:
  - build.sh